#cloud-config

write_files:

  - path: /usr/local/sbin/gateway-route.sh
    permissions: "0755"
    owner: root:root
    content: |
      #!/usr/bin/env bash

      set -euo pipefail

      # https://docs.hetzner.com/networking/networks/faq/#how-do-i-setup-my-own-router
      GATEWAY_IP="${ gateway_ip }"

      IFACE=$(ip -o -4 addr show | awk '$4 ~ /^10\./ {print $2; exit}')

      if [[ -z "$${IFACE:-}" ]]; then
        echo "Failed to detect private interface" >&2
        exit 1
      fi

      ip route replace default via "$GATEWAY_IP" dev "$IFACE"

      echo "Default route configured through $GATEWAY_IP on $IFACE"

  - path: /etc/systemd/system/gateway-route.service
    permissions: "0644"
    owner: root:root
    content: |
      [Unit]
      Description=Configure default route through private gateway
      After=network-online.target
      Wants=network-online.target

      [Service]
      Type=oneshot
      ExecStart=/usr/local/sbin/gateway-route.sh
      ExecReload=/usr/local/sbin/gateway-route.sh
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target

  - path: /etc/systemd/resolved.conf
    content: |

      DNS=185.12.64.1 1.1.1.1
      FallbackDNS=8.8.8.8 9.9.9.9 208.67.222.222
    append: true

runcmd:

  - systemctl daemon-reload
  - systemctl enable gateway-route.service
  - systemctl start gateway-route.service
  - systemctl restart systemd-resolved
